### ISSUE TITLE
Consider uploading to PyPI

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/storygraph-suite#1]
Are there any barriers beyond learning the usual process of pushing this tool to PyPI? This process has been performed by multiple WS-DLers, so it should be straightforward for this tool _unless_ there is a reason not to do so.

/cc @anwala

**Comment by anwala** [comment]
Hello @machawk1, 

No barriers, it's on the to do list. Hoping to get to it very soon.

**Comment by machawk1** [comment]
Hey @anwala, by being a GitHub issue, it is now officially on the to-do list. 😄 

If there are other to-dos, you may want to create GitHub issues for them. This might facilitate collaboration for those that want to get involved will be able to see outstanding tasks.

**Comment by anwala** [comment]
Great idea! Thanks!

**Comment by anwala** [comment]
Hello again @machawk1,

You [can](https://github.com/oduwsdl/storygraph-suite/commit/712046a425def4f3ed5695837e241ebc92025c6e) now install sgsuite via: `pip install sgsuite`
